### ISSUE TITLE
Navigate To Index From Other Pages Error

### ISSUE THREAD

**Issue by Favorlock** [CraigVella/Statistician_Web#5]
So after spending 3 hours on setting up a local server that I could use to test this and use for when my friends and I play I came across a little error which I figured was a very simple fix, and of course it is very simple to fix.

So basically if you click on the My Minecraft World Stats link to take you back to the main page I'll get an ftp view of the index that shows all of the files and its just black text on a white background. So basically I added index.php to part of the code on the index and I fixed the problem for all of the pages. I would post the snippet of code I changed if I knew how, but alas I don't, and github doesn't want to make it any easier for me.

**Comment by feildmaster** [comment]
Should be fixed.
