### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by romainhk** [CraigVella/Statistician_Web#8]
I've made a french translation of Statistician Web ( http://romhk.free.fr/data/fr.php.zip ). There is just one thing that I didn't get : what is "Fire tick death" ? Does it involve cactus ?

I'd have to put a header() function to handle accentuated characters (charset utf-8) but I can convert it with html entities if you want.

**Comment by Dazzel** [comment]
I think fire tick death is when you get lit and burned down :D
