### ISSUE TITLE
Add template Engine

### ISSUE THREAD

**Issue by Dazzel** [CraigVella/Statistician_Web#9]
It would be easyer to use an template engine like smarty or a small self-written one than using PHP and HTML in on template.

**Comment by feildmaster** [comment]
I was going to do this. but the plugin went inactive and i haven't decided if i wanted to take it over.

With all my plugins.

**Comment by Dazzel** [comment]
Yeah. It is inactive. We are working on a fork and we wanted to take it over but he didnt answered :(

But if you want to help us please send a message to https://github.com/Crimsonfoxy
